"""migracion inicial

Revision ID: 536522e7e670
Revises: 
Create Date: 2022-11-09 22:36:04.233617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536522e7e670'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.Column('correo', sa.String(length=45), nullable=False),
    sa.Column('telfono', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Usuarios')
    # ### end Alembic commands ###
