"""agrege relacion tareas usuarios

Revision ID: 6ae5acd4837e
Revises: 654f63be3161
Create Date: 2022-11-10 19:47:45.669071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae5acd4837e'
down_revision = '654f63be3161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tareas', 'Usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.drop_column('tareas', 'usuario_id')
    # ### end Alembic commands ###
