"""cambie columna telefono 

Revision ID: d1cd1479b0a8
Revises: 6ae5acd4837e
Create Date: 2022-11-10 21:14:00.691774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1cd1479b0a8'
down_revision = '6ae5acd4837e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('telefono', sa.String(length=15), nullable=True))
    op.drop_column('Usuarios', 'telfono')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('telfono', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('Usuarios', 'telefono')
    # ### end Alembic commands ###
